#!/bin/bash
set -eu -o pipefail
id=${1:-default}
len=${2:-24}

log_n=${3:-17}
n=$((2**$log_n))
p=${4:-4}
r=${5:-8}

echo "memory: $((128*$n*$r*$p/(1024*1024)))M"



gen_len=$((2*len))

echo -n "password: "
read -s password
echo

start_time=$(date +%s)


id_hash=$(echo -n "$id" | sha512sum -b - | awk '{print $1;}')
salt=$(echo -n "$id_hash" | cut -c 1-64)
f_salt=$(echo -n "$id_hash" | rev | cut -c 1-64)


echo 'generating...'

full_derived=$(openssl kdf -binary -keylen $gen_len -kdfopt pass:"$password" -kdfopt hexsalt:"$salt" -kdfopt n:"$n" -kdfopt r:"$r" -kdfopt p:"$p" SCRYPT | base64 | tr -d '=/+\n')
derived=$(echo -n "$full_derived" | cut -c1-"$len" | tr -d '\n')
digest=$(echo -n "$derived" | sha512sum -b - | awk '{print $1;}')
fingerprint=$(openssl kdf -binary -keylen 8 -kdfopt pass:"$digest" -kdfopt hexsalt:"$f_salt" -kdfopt n:"$n" -kdfopt r:"$r" -kdfopt p:"$p" SCRYPT | xxd -p | cut -c1-7)

end_time=$(date +%s)

echo $(($end_time - $start_time)) seconds
echo "derived: $derived"
echo "fingerprint: $fingerprint"

: "
              test vectors
              ------------
---
'' 64 15 1 16
password: ''
derived: ZJ6NkBktAgDfLTsMt1IJJKoNSG2tnsKP638E6kZQv4PhLlVtcgh8JzVCipwyklgS
fingerprint: 2be6402
---
'abc123' 24 17 4 8
password: 'abc123'
derived: BVbCbl7QfZ9RLHVHjXs1vtfp
fingerprint: 6cedf75
---
'passwordid'
password: 'password'
derived: hjj6c5RxZKzmZxtatMdkBz9d
fingerprint: b268618
---
0123456789ABCDEF 32 12 2 16
password: 'let me in'
derived: s5Jk09SizsAT9zmWEti4w9sq732EpWlD
fingerprint: 55f5816
---
ZJ6NkBktAgDfLTsMt1IJJKoNSG2tnsKP638E6kZQv4PhLlVtcgh8JzVCipwyklgS 68
password: 'ZJ6NkBktAgDfLTsMt1IJJKoNSG2tnsKP638E6kZQv4PhLlVtcgh8JzVCipwyklgS'
derived: GmokdVKVdHwllaPUYAw2SX8Beno9PnbMM0MDYRliGXhnhZTJtbGw8dxeNVUuaJ00CalO
fingerprint: 5467acd
"
