#!/bin/bash
set -eu -o pipefail
id=${1:-default}
len=${2:-24}
len=$((10#$len))

log_n=${3:-17}
n=$((2**$log_n))
p=${4:-4}
r=${5:-8}

echo "memory: $((128*$n*$r*$p/(1024*1024)))M"



gen_len=$((2 * len))

echo -n "password: "
read -s password
echo

start_time=$(date +%s)


salt_src=$(echo -n "$id $len" | sha512sum -b - | awk '{print $1;}')
salt=$(echo -n "$salt_src" | cut -c 1-64)
f_salt=$(echo -n "$salt_src" | rev | cut -c 1-64)


echo 'generating...'

full_derived=$(openssl kdf -binary -keylen $gen_len -kdfopt pass:"$password" -kdfopt hexsalt:"$salt" -kdfopt n:"$n" -kdfopt r:"$r" -kdfopt p:"$p" SCRYPT | base64 | tr -d '=/+\n')
full_len=${#full_derived}
tail_len=$(($full_len - $len))
derived=$(echo -n "$full_derived" | cut -c1-"$len" | tr -d '\n')
rev_tail=$(echo -n "$full_derived" | rev | cut -c1-"$tail_len" | tr -d '\n')

fingerprint=$(openssl kdf -binary -keylen 8 -kdfopt pass:"$rev_tail" -kdfopt hexsalt:"$f_salt" -kdfopt n:"$n" -kdfopt r:"$r" -kdfopt p:"$p" SCRYPT | xxd -p | cut -c1-7)

end_time=$(date +%s)

echo $(($end_time - $start_time)) seconds
echo "derived: $derived"
echo "fingerprint: $fingerprint"

: "
              test vectors
              ------------
---
'' 0064 15 1 16
password: ''
derived: Shw02UlQFON4YXqLNVp7iFOKSlazflzzdLcxEvZPcy0x2faLuCLYgiInFcnrKYtw
fingerprint: 770517f
---
'abc123' 24 17 4 8
password: 'abc123'
derived: LCrwUMADyTDBiLHHjQTrn6d9
fingerprint: 55fc31a
---
abc123 0023
password: abc123
derived: Oa3cI2eh5scqWR2u7JMa2dN
fingerprint: d9a8bd0
---
'passwordid'
password: 'password'
derived: 3RoM93oLUmZgoiYo1JXoVAIA
fingerprint: 5bf089a
---
0123456789ABCDEF 32 12 2 16
password: 'let me in'
derived: oH3tpprpN2cW9tn6DeCcB0GiP7Q8N79o
fingerprint: 6071846
---
ZJ6NkBktAgDfLTsMt1IJJKoNSG2tnsKP638E6kZQv4PhLlVtcgh8JzVCipwyklgS 68
password: 'ZJ6NkBktAgDfLTsMt1IJJKoNSG2tnsKP638E6kZQv4PhLlVtcgh8JzVCipwyklgS'
derived: 2Pvr0euzhWmlutaiu0qpm4Bs972uwXVT2OEozABBv8XyzOtHFbjRII9z7mmxkOAwOBEs
fingerprint: 7b67bf0
"
